/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


@author Kumar Hemant 
*/

#include <stdio.h>
#include <math.h>

#define LIMIT 4000000

int main() 
{
 	int i, n;
 	int evenFibSum = 0 ;
	printf("Enter number to calculate  fibonacci series: ");
	scanf("%d", &n);	

	printf("\n Printing fibonacci series:...\n");

	for(i=0; i<=n && fib(i) < LIMIT ; i++)
	{
		printf("%8d", fib(i));
 		if(fib(i)%2 == 0 && fib(i) <= LIMIT)
 		{
 		 if(fib(i) >= LIMIT || n)	
 		 evenFibSum = evenFibSum + fib(i) ;
		}
	//if(i < n && fib(i) > LIMIT)
	// printf("LIMIT OFFSETS");	 
 	}
printf("\n");
printf("calculating sum of even valued fibonacci numbers...\n");	
printf("\nSum of even numbers of Fibonacci series: %d\n\n", evenFibSum);

}


int	fib(int n){
    if(n==0)
    	return 0;
    else if(n==1)
    	return 1;
    else	 
    	return fib(n-1) + fib(n-2);  
}

